### ISSUE TITLE
Pool Namspaces

### ISSUE THREAD

**Issue by zabawaba99** [CloudCom/fireload#4]
Does the pool need to have a slice of pointers?

**Comment by MrGossett** [comment]
Not necessarily. I used pointers to keep memory allocation low, and also because it made the test easier.

I'm currently playing around with stdlib's `container/ring` for `Nodes` instead of a `[]*Namespace`.

**Comment by zabawaba99** [comment]
Cool deal. I'd say link the PR to this issue when you get the branch ready
